### ISSUE TITLE
Why disable swap in bastion?

### ISSUE THREAD

**Issue by NicolasCARPi** [outscale-dev/osc-k8s-rke-cluster#5]
Clearly not an issue, more of a question: is there a reason why [swap is disabled](https://github.com/outscale-dev/osc-k8s-rke-cluster/blob/4f557be98a62e0dd17dc070d609efb411a111436/bastion/playbook.yaml#L25-L27) for bastion host?

**Comment by jerome-jutteau** [comment]
Hi,

From [kubernetes-the-hard-way](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/09-bootstrapping-kubernetes-workers.md#disable-swap) documentation:

> By default the kubelet will fail to start if [swap](https://help.ubuntu.com/community/SwapFaq) is enabled. It is [recommended](https://github.com/kubernetes/kubernetes/issues/7294) that swap be disabled to ensure Kubernetes can provide proper resource allocation and quality of service.

Note that swap would probably be already disabled as official Linux OMI does not have swap partition included by default.

**Comment by jerome-jutteau** [comment]
Also there are no real need to disable swap for bastion host specific usage but this machine is used in terraform to create an OMI used for workers and control-plane.

**Comment by NicolasCARPi** [comment]
Thank you, that's good to know! :)
